ToDo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from registration import views as reviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', reviews.register, name='register'),
    path('', include('todo_app.urls')),
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
]

todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'

urlpatterns = [
    path('create/', views.todo_create, name='todo_create'),
    path('<int:id>/', views.todo_list, name='todo_list'),
    path('view/', views.view, name='view'),

]

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User


class ToDoList(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='todolist', null=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Item(models.Model):
    todolist = models.ForeignKey(
        ToDoList, on_delete=models.CASCADE, related_name='item')
    text = models.CharField(max_length=255)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

todo_app/forms.py
from django import forms


class CreateNewList(forms.Form):
    name = forms.CharField(label='Name', max_length=255)

ToDo/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html', {})


def profile(request):
    return render(request, 'profile.html', {})

todo_app/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from .forms import CreateNewList
from django.urls import reverse
from .models import ToDoList, Item
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist


@login_required(login_url='/login/')
def todo_create(request):
    if request.method == 'POST':
        form = CreateNewList(request.POST)

        if form.is_valid():
            n = form.cleaned_data["name"]
            t = ToDoList(name=n)
            t.save()
            request.user.todolist.add(t)

            return HttpResponseRedirect(reverse('todo_app:todo_list', args=(t.id,)))
    else:
        form = CreateNewList()

    return render(request, 'todo_app/todo_create.html', {'form': form})


@login_required(login_url='/login/')
def todo_list(request, id):
    # ls = get_object_or_404(ToDoList, id=id)
    try:
        ls = ToDoList.objects.get(id=id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('todo_app:view'))

    if ls in request.user.todolist.all():
        if request.method == "POST":
            if request.POST.get("save"):
                for item in ls.item_set.all():
                    p = request.POST

                    if "clicked" == p.get("c" + str(item.id)):
                        item.complete = True
                    else:
                        item.complete = False
                    if "text" + str(item.id) in p:
                        item.text = p.get("text" + str(item.id))

                    item.save()
            elif request.POST.get("add"):
                new_item = request.POST.get("new")
                if new_item != "":
                    ls.item_set.create(text=new_item, complete=False)
                else:
                    print("invalid")

            for item in ls.item_set.all():
                if request.POST.get(f'd{item.id}'):
                    p = request.POST

                    if "Delete" == p.get("d" + str(item.id)):
                        item.delete()

        return render(request, 'todo_app/todolist.html', {'ls': ls})
    else:
        return HttpResponseRedirect(reverse('todo_app:view'))


@login_required(login_url='/login/')
def view(request):
    return render(request, 'todo_app/view.html', {})

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>
    {% block title %}
    {% endblock  %}
    </title>
  </head>
  <body>
    {% include 'navbar.html' %}

<div class="container">
    <div id="content" name="content">
        <div class="main">
            <div class="row justify-content-center">
                <div class="col-8">
                    <h1 class="mt-2">
                    {% block page_name %}
                    
                    {% endblock  %} 
                    </h1>
                    <hr class="mt-0 mb-4">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock  %}


{% block content %}
<h1>Home</h1.
{% endblock  %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <a href={% url 'home' %}>
    <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="Responsive image" style="width:40px">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'view' %}active{% endif %}" href={% url 'todo_app:view' %}>VIEW LISTS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'todo_create' %}active{% endif %}" href={% url 'todo_app:todo_create' %}>CREATE NEW LIST</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item {% if request.resolver_match.url_name == 'profile' %}active{% endif %}" href={% url 'profile' %}>PROFILE</a>
            <a class="dropdown-item {% if request.resolver_match.url_name == 'password_change' %}active{% endif %}" href={% url 'password_change' %}>CHANGE PASSWORD</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href={% url 'logout' %}>LOG OUT</a>
          </div>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href={% url 'login' %}>LOG IN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}" href={% url 'register' %}>SIGN UP</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/profile.html
{% extends 'base.html' %}

{% block title %}
Profile
{% endblock  %}


{% block page_name %}
Your Profile
{% endblock  %}

{% block content %}
<h1>Profile</h1>
{% endblock  %}

todo_app/templates/todo_app/todo.html
{% extends 'base.html' %}

{% block title %}
ToDo
{% endblock  %}

{% block content %}
<h1>Hello</h1>
{% endblock  %}

todo_app/templates/todo_app/todo_create.html
{% extends 'base.html' %}

{% block title %}
Create
{% endblock  %}

{% block page_name %}
Create a New To Do List
{% endblock  %}

{% block content %}
{% comment %} <h3>Create a New To Do List</h3> {% endcomment %}
	<br>
	<form method="post" action={% url 'todo_app:todo_create' %} class="form-group">
		{% csrf_token %}
		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="save" type="submit" class="btn btn-outline-success">Create</button>
	  		</div>
	  		{{form.name}}
		</div>
	</form>
{% endblock  %}

todo_app/templates/todo_app/todolist.html
{% extends 'base.html' %}
{% block title %}
ToDo List
{% endblock  %}

{% block page_name %}
Todo List
{% endblock  %}

{% block content %}
	<h2>{{ls.name}}</h2>
	<form method="post", action="#">
		{% csrf_token %}

		{% for item in ls.item.all%}
			<div class="input-group mb-3">
	  			<div class="input-group-prepend">
	    			<div class="input-group-text">
	      				<input type="checkbox" name="c{{item.id}}" value="clicked" aria-label="Checkbox for following text input" {% if item.complete %} checked {% endif %}>
	    			</div>
	  			</div>
					<input type="text" name="text{{item.id}}" value="{{item.text}}" class="form-control" aria-label="Text input with checkbox">
					<li class="list-inline-item">
						<button class="btn btn-outline-danger" type="submit" value="Delete" name="d{{item.id}}">Delete</button>
					</li>
			</div>
		{% endfor %}

		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="add", value="add", type="submit", class="btn btn-outline-success">Add New</button>
	  		</div>
	  		<input type="text" name="new" value="" class="form-control">
	  		
		</div>
		<br>
		<button name="save", value="save", type="submit", class="btn btn-outline-success">Save</button>
	</form>
{% endblock  %}

todo_app/templates/todo_app/view.html
{% extends 'base.html' %}
{% block title %}
View ToDo List
{% endblock  %}

{% block page_name %}
View ToDo Lists
{% endblock  %}

{% block content %}
    <ul class="list-group">
		{% for td in user.todolist.all %}
				<li class="list-group-item"><a href="/{{td.id}}"><h3>{{td.name}}</h3></a></li>
		{% endfor %}
    </ul>
{% endblock  %}